# Generated by Django 2.2.1 on 2019-06-06 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineapp', '0004_auto_20190606_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='mocktest1',
            name='problem2',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mocktest1',
            name='problem3',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mocktest1',
            name='problem4',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mocktest1',
            name='problem5',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
