# Generated by Django 2.2.1 on 2019-06-06 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineapp', '0006_auto_20190606_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='dob',
            field=models.DateField(default='1998-09-22', null=True),
        ),
    ]
