# Generated by Django 2.2.1 on 2019-06-07 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineapp', '0007_auto_20190606_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
