# Generated by Django 2.2.1 on 2019-06-17 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Innings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('innings_no', models.IntegerField()),
                ('batting_team', models.CharField(default='None', max_length=128)),
                ('bowling_team', models.CharField(default='None', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Over',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bowler', models.CharField(default='None', max_length=128)),
                ('over_no', models.IntegerField()),
                ('is_super_over', models.BooleanField()),
                ('innings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cricbuzzapp.Innings')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('match_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('city', models.CharField(default='None', max_length=128)),
                ('date', models.DateField(default='1998-09-22', null=True)),
                ('team1', models.CharField(default='None', max_length=128)),
                ('team2', models.CharField(default='None', max_length=128)),
                ('toss_winner', models.CharField(default='None', max_length=128)),
                ('toss_decision', models.CharField(default='None', max_length=128)),
                ('result', models.CharField(default='None', max_length=128)),
                ('dl_applied', models.BooleanField(default=False)),
                ('winner', models.CharField(default='None', max_length=128)),
                ('win_by_runs', models.IntegerField()),
                ('win_by_wickets', models.IntegerField()),
                ('player_of_the_match', models.CharField(default='None', max_length=128)),
                ('venue', models.CharField(default='None', max_length=128)),
                ('umpire1', models.CharField(default='None', max_length=128)),
                ('umpire2', models.CharField(default='None', max_length=128)),
                ('umpire3', models.CharField(default='None', max_length=128)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cricbuzzapp.Season')),
            ],
        ),
        migrations.AddField(
            model_name='innings',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cricbuzzapp.Match'),
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ball_no', models.IntegerField()),
                ('batsman', models.CharField(default='None', max_length=128)),
                ('non_striker', models.CharField(default='None', max_length=128)),
                ('wide_runs', models.IntegerField()),
                ('bye_runs', models.IntegerField()),
                ('legbye_runs', models.IntegerField()),
                ('noball_runs', models.IntegerField()),
                ('penalty_runs', models.IntegerField()),
                ('batsman_runs', models.IntegerField()),
                ('extra_runs', models.IntegerField()),
                ('total_runs', models.IntegerField()),
                ('player_dismissal', models.CharField(max_length=128)),
                ('dismissal_kind', models.CharField(max_length=128)),
                ('fielder', models.CharField(max_length=128)),
                ('over', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cricbuzzapp.Over')),
            ],
        ),
    ]
