# Generated by Django 2.2.1 on 2019-06-17 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricbuzzapp', '0003_auto_20190617_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='batsman',
            field=models.CharField(blank=True, default='None', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='dismissal_kind',
            field=models.CharField(blank=True, default='None', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='fielder',
            field=models.CharField(blank=True, default='None', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='non_striker',
            field=models.CharField(blank=True, default='None', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='player_dismissal',
            field=models.CharField(blank=True, default='None', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='innings',
            name='batting_team',
            field=models.CharField(blank=True, default='None', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='innings',
            name='bowling_team',
            field=models.CharField(blank=True, default='None', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='over',
            name='bowler',
            field=models.CharField(blank=True, default='None', max_length=128, null=True),
        ),
    ]
